name: Verify

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      terraform: >-
        ${{ steps.detection.outcome == 'skipped' ||
            steps.detection.outputs.terraform }}
      linux-shared-lib: >-
        ${{ steps.detection.outcome == 'skipped' ||
            steps.detection.outputs.linux-shared-lib }}
    steps:
      - name: Detect changes
        id: detection
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@v3
        with:
          filters: |
            linux-shared-lib:
              - linux-shared-lib/**
            terraform:
              - terraform/**
      - name: Empty step
        run: echo "empty step"

  verify-linux-shared-lib:
    name: Verify linux-shared-lib
    needs: detect-changes
    if: needs.detect-changes.outputs.linux-shared-lib == 'true'
    uses: ./.github/workflows/verify-linux-shared-lib.yaml

  verify-terraform:
    name: Verify terraform
    needs: detect-changes
    if: needs.detect-changes.outputs.terraform == 'true'
    uses: ./.github/workflows/verify-terraform.yaml

  conclusion:
    name: Conclusion
    needs:
      # list all verification jobs here
      - verify-linux-shared-lib
      - verify-terraform
    if: always()
    runs-on: ubuntu-latest
    env:
      HAS_FAILURE: ${{ contains(needs.*.outcome, 'failure') }}
    steps:
      - name: Report failure
        if: env.HAS_FAILURE == 'true'
        run: |
          echo "Some jobs failed"
          exit 1
      - name: Report success
        run: echo "no failures"
